#!/usr/bin/with-contenv sh

IP=$(hostname -i)
PDNS_DATA=${PDNS_DATA:-/var/services/powerdns}
PDNS_LOG=${PDNS_LOG:-/var/services/powerdns/log}
DNS_PRIMARY=${DNS_PRIMARY:-$HOSTNAME}
mkdir -p "$PDNS_DATA" "$PDNS_LOG"

# CONFIGURE WORKER
if grep "PDNS_DATA" "/etc/desk/worker.conf"; then
    echo "* configure worker.conf for pdns"
    sed -i -e "s#-HOSTNAME-#${HOSTNAME}#" -e "s#-DNS_PRIMARY-#${DNS_PRIMARY}#" \
            -e "s#-PDNS_DATA-#${PDNS_DATA}#" \
        /etc/desk/worker.conf
fi

# CONFIGURE PDNS
if grep "PDNS_DATA" "/etc/powerdns/pdns.d/pdns.local.conf"; then
    echo "* configure pdns"
    sed -i \
        -e "s/-IP-/${IP}/" \
        -e "s/-HOSTNAME-/${HOSTNAME}/" \
        -e "s#-PDNS_DATA-#${PDNS_DATA}#" \
        /etc/powerdns/pdns.d/*
fi

# SETUP PDNS DATABASE
if [ ! -f "$PDNS_DATA/pdns_${HOSTNAME}.sqlite3" ]; then
    sqlite3 $PDNS_DATA/pdns_${HOSTNAME}.sqlite3 < /etc/powerdns/powerdns-setup.sql
fi

/usr/sbin/pdns_server --config-dir=/etc/powerdns --daemon=no --guardian=no >> $PDNS_LOG/pdns.${HOSTNAME}.log 2>&1
