---
# file: roles/dns/tasks/main.yml
- name: remove not needed files
  file: path={{ item }} state=absent
  with_items:
    - /etc/powerdns/bindbackend.conf
    - /etc/powerdns/pdns.d/pdns.simplebind.conf

- name: add dns a service
  copy: src=../dns/etc/service/pdns dest=/etc/service/ mode=0755


- name: add as worker service
  copy: src=../dns/etc/service/worker dest=/etc/service/ mode=0755
