[couchdb]
uri = http://admin:admin@172.16.172.1:5984
db  = desk_drawer

[worker]
is_foreman = true
dns = powerdns:ns1.localhost

[powerdns]
name = ns1.localhost
backend = sqlite
db = /etc/powerdns/dns.db
