---
# file: parts/couchdb-testdata.yml

- hosts: foremanservers
  tasks:
  - name: create test data
    command: "curl -H 'Content-Type: application/json' -XPOST http://cdb_1:5984/desk_drawer/ --user admin:admin -d @tests/fixtures/{{ item }}"
    args:
      chdir: /projects/desk/desk
    with_items:
      - couchdb-client-test.json
      - couchdb-dns-test1.test.json
      - couchdb-dns-test2.test.json
      - couchdb-map-ips.json
      - couchdb-template-dns.json
