---
# file: roles/couchdb/tasks/main.yml

- name: stop couchdb
  command: supervisorctl stop couchdb

- name: copy couchdb local.ini, desk.ini
  copy: src=../couchdb/etc/couchdb/{{ item }} dest=/usr/local/etc/couchdb/{{ item }}
  with_items:
    - local.ini
    - local.d/desk.ini

# - name: remove old couchdb files # doesn't work volume still mounted
#   file: path=/usr/local/var/lib/couchdb state=absent

- name: ensure right permissions for couchdb dir
  command: chown -R couchdb:couchdb /projects/desk/desk/var/lib/couchdb

- name: start couchdb
  command: supervisorctl start couchdb
