---
# file: roles/couchdb/tasks/main.yml

- name: copy couchdb local.ini, desk.ini
  copy: src=../couchdb/etc/couchdb/{{ item }} dest=/usr/local/etc/couchdb/{{ item }}
  with_items:
    - local.ini
    - local.d/desk.ini

- name: create couchdb data dir
  file: path=/var/data/couchdb state=directory
        owner=couchdb group=couchdb

- name: start couchdb
  command: creates="/etc/service/couchdb"
           mv /etc/service-off/couchdb /etc/service/couchdb
