---
# file: roles/worker/tasks/main.yml

- name: create /etc/desk/worker.conf
  file: path=/etc/desk state=directory

- name: create dns worker.conf
  when: worker_type == "dns"
  template: src=../../dns/etc/desk/worker.conf.j2 dest=/etc/desk/worker.conf

- name: create master worker.conf
  when: worker_type == "master"
  copy: src=../../master/etc/desk/worker.conf dest=/etc/desk/worker.conf

- name: add desk to site-packages
  command: /var/py27/bin/python setup.py develop
  args:
    chdir: /projects/python/desk
    creates: /var/py27/lib/python2.7/site-packages/desk.egg-link
