#!/usr/bin/with-contenv sh

# PUT EXTRA_HOST in /etc/hosts
if [ -n "$EXTRA_HOSTS" ]; then
  FIRST_ENTRY=$(echo $EXTRA_HOSTS|awk -F'[/ |;]'  '{ print $2 }')
  if ! grep -q "$(echo $FIRST_ENTRY)" /etc/hosts; then # only do it once
    echo -e "$(eval "echo -e \"$EXTRA_HOSTS\"")"| tr ";" "\n" >> /etc/hosts
  fi
fi

WORKER_TYPE=${WORKER_TYPE:-worker} # set to worker as default
TESTING=${TESTING:-NO}
FQHOSTNAME=$(hostname)
START_WORKER=${START_WORKER:-YES}
WORKER_LOG=${WORKER_LOG:-/var/services/worker/log}

# CREATE DIRS
mkdir -p "$WORKER_LOG"

# CONFIGURE WORKER COUCHDB
if grep -q "COUCHDB_ADMINPASS" "/etc/desk/worker.conf"; then
    echo "* configure couchdb worker.conf"
    sed -i \
        -e "s#-COUCHDB_ADMINPASS-#${COUCHDB_ADMINPASS}#" \
        -e "s#-COUCHDB_ADMIN-#${COUCHDB_ADMIN}#" \
      /etc/desk/worker.conf
fi

# RUN STUFF FOR FOREMAN, CREATE DATABASE
if [ $WORKER_TYPE = "foreman" ]; then
    wget -q --retry-connrefused -t 10 http://cdb:5984/ # wait for couchdb to get up
    # creating desk_drawer database
    curl -Is -u $COUCHDB_ADMIN:$COUCHDB_ADMINPASS http://cdb:5984/desk_drawer|cat|grep -q -E "HTTP.*200|HTTP.*401"
    if [ $? -ne 0 ]; then # db desk_drawer does not exist
        cd /opt/app/desk && python ./dworker install-db
        echo "* created desk_drawer database"
    fi

    # Setup Fonts for invoices
    if [ -d "/root/.fonts" ]; then
        echo "* cleaning font cache"
        /usr/bin/fc-cache -f
    fi
fi

# RUN IN NORMAL CASE
if [ "$TESTING" == "NO" ]; then
    # REGISTER WORKER
    # wait for db created
    until $(curl -Is -u $COUCHDB_ADMIN:$COUCHDB_ADMINPASS http://cdb:5984/desk_drawer|cat|grep -q -E "HTTP.*200"); do
        sleep 1
        echo "* wait desk_drawer db"
    done
    curl -Is -u "${COUCHDB_ADMIN}:${COUCHDB_ADMINPASS}" "http://cdb:5984/desk_drawer/worker-${FQHOSTNAME}"|cat|grep -q -E "HTTP.*404"
    if [ $? -eq 0 ]; then # worker doesn't exist
        cd /opt/app/desk && python ./dworker install-worker
        echo "* registred worker"
    fi
fi

if [ "$START_WORKER" == "YES" ]; then
    rm /etc/services.d/worker/down
fi
