cdb:
  image: yvess/desk-couchdb
  hostname: cdb
  environment:
    - TERM=xterm-256color
  volumes:
    - ../:/opt/app/
    ~/src:/opt/src
    ~/env:/opt/env
  volumes_from:
    - desk_data
  ports:
    - "5984:5984"

dnsa:
  image: yvess/desk-dns
  hostname: dnsa.test
  environment:
    - TERM=xterm-256color
  volumes:
    - ../:/opt/app/
  volumes_from:
    - desk_data
  links:
    - cdb
  ports:
    - "1053:53"
  # command: tail -f /dev/null

dnsb:
  image: yvess/desk-dns
  hostname: dnsb.test
  environment:
    - TERM=xterm-256color
  volumes:
    - ../:/opt/app/
  volumes_from:
    - desk_data
  links:
    - cdb
  ports:
    - "2053:53"
  # command: tail -f /dev/null

foreman:
  image: yvess/desk-worker
  hostname: foreman
  environment:
    - TERM=xterm-256color
  volumes:
    - ../:/opt/app/
  volumes_from:
    - desk_data
  links:
    - cdb
    - dnsa
    - dnsb
  # command: tail -f /dev/null

