#!/usr/bin/env python
# coding: utf-8
from __future__ import absolute_import, print_function, unicode_literals, division  # python3

import sys
from ConfigParser import SafeConfigParser
import argparse

sys.path.append("../")
from desk.cmd.run import Worker, Foreman
from desk.cmd.install import InstallCommand
from desk.cmd.run import RunCommand


def setup_parser():
    """create the command line parser / config file reader """

    defaults = {
        "couchdb_uri": "http://localhost:5984",
        "couchdb_db": "desk_drawer",
        "worker_daemon": True,
        "worker_is_foreman": False,
    }
    config = {
        'args': ["-c", "--config"],
        'kwargs': {
            'dest': "config",
            'default': "/etc/desk/worker.conf",
            'help': "path to the config file, default: /etc/desk/worker.conf",
            'metavar': "FILE"
        }
    }
    boolean_types = ['worker_daemon', 'worker_is_foreman']
    conf_sections = ['couchdb', 'powerdns', 'worker']

    main_parser = argparse.ArgumentParser()
    subparsers = main_parser.add_subparsers(
        dest='command',
        title="subcommands",
        description="available subcommands",
        help="all commands"
    )

    # run parser
    run_parser = subparsers.add_parser(
        'run',
        help="""Worker is the agent for the desk plattform.
                       Command line switches overwrite config file settings""",
    )
    run_parser.add_argument(*config['args'], **config['kwargs'])
    run_parser.add_argument(
        "-o", "--run_once", dest="worker_daemon",
        help="run only once not as daemon", action="store_false", default=True
    )
    run_parser.add_argument(
        "-u", "--couchdb_uri", dest="couchdb_uri",
        metavar="URI", help="connection url of the server"
    )
    run_parser.add_argument(
        "-d", "--couchdb_db", dest="couchdb_db",
        metavar="NAME", help="database of the server"
    )
    run_parser.add_argument(
        "-f", "--foreman", dest="worker_is_foreman",
        help="be the foreman and a worker", action="store_true"
    )

    # install parser
    install_parser = subparsers.add_parser(
        'install',
        help="""install the couchdb design docs""",
    )
    install_parser.add_argument(*config['args'], **config['kwargs'])

    args = main_parser.parse_args()

    # load config files with settings
    # puts them into a dict format "section_option"
    if hasattr(args, 'config') and args.config:
        config = SafeConfigParser()
        if not config.read([args.config]):
            print("Can't open file '{}'".format(args.config))
            sys.exit(0)
        else:
            for section in conf_sections:  # put in here all your sections
                conf_section = {}
                if config.has_section(section):
                    for k, v in config.items(section):
                        section_prop = '{}_{}'.format(section, k)
                        if section_prop in boolean_types:
                            conf_section[section_prop] = config.getboolean(section, k)
                        else:
                            conf_section[section_prop] = config.get(section, k)
                defaults.update(conf_section)

    run_parser.set_defaults(**defaults)
    install_parser.set_defaults(**defaults)
    settings = main_parser.parse_args()

    return settings


if __name__ == "__main__":
    settings = setup_parser()
    if settings.command == 'run':
        worker = RunCommand(settings)
        worker.run()
    elif settings.command == 'install':
        install = InstallCommand(settings)
        install.upload_design_doc()
