#!/usr/bin/with-contenv sh
#set -e

FQHOSTNAME=$(hostname)
WORKER_LOG=${WORKER_LOG:-/var/services/worker/log}

cd /opt/app/desk
sleep 2
echo "* staring worker - $(date)" | tee "${WORKER_LOG}/${FQHOSTNAME}.log"

pid=$$

sigterm() {
    kill -TERM $pid
}

trap sigterm SIGTERM
# start after other /etc/services.d
python -u ./dworker run -v >> "${WORKER_LOG}/${FQHOSTNAME}.log" 2>&1 &
pid=$!
wait
