---
# file: roles/foreman/tasks/main.yml

- name: check for couchdb db
  uri: url="http://cdb_1:5984/desk_drawer"
       user=admin password=admin status_code=404,401,200
  register: db_desk_drawer

- name: install desk db
  when: "db_desk_drawer.status == 404 or db_desk_drawer.status == 401"
  command: "/var/py27/bin/python dworker install-db"
  args:
    chdir: /projects/desk/desk

- name: add as worker service
  copy: src=../foreman/etc/service/worker dest=/etc/service/ mode=0755
