---
# file: roles/worker-register/tasks/main.yml

- name: check for worker doc
  uri: url=http://cdb_1:5984/desk_drawer/worker-{{ ansible_hostname }}
       user=admin password=admin status_code=200,404
  register: worker_doc

- name: install worker
  when: "worker_doc.status == 404"
  command: "/var/py27/bin/python dworker install-worker"
  args:
    chdir: /projects/desk/desk
