---
# file: roles/dns/tasks/main.yml
- name: remove not needed files
  file: path={{ item }} state=absent
  with_items:
    - /etc/powerdns/bindbackend.conf
    - /etc/powerdns/pdns.d/pdns.simplebind.conf

- name: create /etc/desk/worker.conf
  file: path=/etc/desk state=directory
- name: create /etc/desk/worker.conf
  template: src=../../dns/etc/desk/worker.conf.j2 dest=/etc/desk/worker.conf
