#!/command/with-contenv sh

FQHOSTNAME=$(hostname)
WORKER_LOG=${WORKER_LOG:-/var/services/worker/log}

cd /opt/app/desk
echo "* starting worker - $(date)" | tee "${WORKER_LOG}/${FQHOSTNAME}.log"

exec python3 -u ./dworker run -v >> "${WORKER_LOG}/${FQHOSTNAME}.log" 2>&1
